### ISSUE TITLE
[USER REPORTED ERROR] (InplaceVolumetrics) Cannot read properties of undefined (reading 'name')

### ISSUE THREAD

**Issue by rubenthoms** [equinor/webviz#198]
**How to reproduce**
Selected ensemble with grid data.

**Error stack**
```
TypeError: Cannot read properties of undefined (reading 'name')
    at selectDefaultTable (http://localhost:8080/src/modules/InplaceVolumetrics/settings.tsx:112:51)
    at invokePassiveEffectCreate (http://localhost:8080/node_modules/.vite/deps/chunk-NPN4KBMN.js?v=0e4cc094:17338:28)
    at HTMLUnknownElement.callCallback2 (http://localhost:8080/node_modules/.vite/deps/chunk-NPN4KBMN.js?v=0e4cc094:3899:22)
    at Object.invokeGuardedCallbackDev (http://localhost:8080/node_modules/.vite/deps/chunk-NPN4KBMN.js?v=0e4cc094:3924:24)
    at invokeGuardedCallback (http://localhost:8080/node_modules/.vite/deps/chunk-NPN4KBMN.js?v=0e4cc094:3958:39)
    at flushPassiveEffectsImpl (http://localhost:8080/node_modules/.vite/deps/chunk-NPN4KBMN.js?v=0e4cc094:17400:17)
    at unstable_runWithPriority (http://localhost:8080/node_modules/.vite/deps/chunk-NPN4KBMN.js?v=0e4cc094:351:20)
    at runWithPriority$1 (http://localhost:8080/node_modules/.vite/deps/chunk-NPN4KBMN.js?v=0e4cc094:8872:18)
    at flushPassiveEffects (http://localhost:8080/node_modules/.vite/deps/chunk-NPN4KBMN.js?v=0e4cc094:17304:22)
    at http://localhost:8080/node_modules/.vite/deps/chunk-NPN4KBMN.js?v=0e4cc094:17223:19
```

**Component stack**
```
    at settings (http://localhost:8080/src/modules/InplaceVolumetrics/settings.tsx:93:3)
    at ErrorBoundary (http://localhost:8080/src/framework/components/ErrorBoundary/errorBoundary.tsx:2:8)
    at div
    at Setting (http://localhost:8080/src/framework/components/Settings/private-components/setting.tsx:25:44)
    at div
    at Settings (http://localhost:8080/src/framework/components/Settings/settings.tsx:23:52)
    at div
    at div
    at ResizablePanels (http://localhost:8080/src/lib/components/ResizablePanels/resizablePanels.tsx:32:13)
    at div
    at QueryClientProvider (http://localhost:8080/node_modules/.vite/deps/chunk-SLWS6KDX.js?v=0e4cc094:2795:3)
    at CustomQueryClientProvider (http://localhost:8080/src/framework/providers/QueryClientProvider.tsx:23:24)
    at AuthProvider (http://localhost:8080/src/framework/providers/AuthProvider.tsx:29:43)
    at App (http://localhost:8080/src/App.tsx:30:9)
```

**Comment by anders-kiaer** [comment]
We have since then reworked `InplaceVolumetrics` - considering the user report as stale. Closing this.
