### ISSUE TITLE
Show curated backend errors in frontend

### ISSUE THREAD

**Issue by anders-kiaer** [equinor/webviz#86]
Currently the timeseries API can fail with a 500 response, ending up with an infinitely loading spinner in the frontend.

Checking the backend log we see this:
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/appuser/.local/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/appuser/.local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/home/appuser/.local/lib/python3.8/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/home/appuser/.local/lib/python3.8/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/appuser/.local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/appuser/.local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/appuser/.local/lib/python3.8/site-packages/starsessions/middleware.py", line 138, in __call__
    await self.app(scope, receive, send_wrapper)
  File "/home/appuser/.local/lib/python3.8/site-packages/starlette/middleware/base.py", line 106, in __call__
    response = await self.dispatch_func(request, call_next)
  File "/home/appuser/backend/./src/fastapi_app/auth/enforce_logged_in_middleware.py", line 66, in dispatch
    response = await call_next(request)
  File "/home/appuser/.local/lib/python3.8/site-packages/starlette/middleware/base.py", line 80, in call_next
    raise app_exc
  File "/home/appuser/.local/lib/python3.8/site-packages/starlette/middleware/base.py", line 69, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/home/appuser/.local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/home/appuser/.local/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/appuser/.local/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/appuser/.local/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/appuser/.local/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/appuser/.local/lib/python3.8/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/home/appuser/.local/lib/python3.8/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/appuser/.local/lib/python3.8/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/home/appuser/.local/lib/python3.8/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "/home/appuser/.local/lib/python3.8/site-packages/fastapi/routing.py", line 165, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/home/appuser/.local/lib/python3.8/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/home/appuser/.local/lib/python3.8/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/appuser/.local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/appuser/.local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/appuser/backend/./src/fastapi_app/routers/timeseries/router.py", line 59, in get_realizations_vector_data
    sumo_vec_arr = access.get_vector(vector_name=vector_name, resampling_frequency=sumo_freq, realizations=realizations)
  File "/home/appuser/backend/./src/services/sumo_access/summary_access.py", line 155, in get_vector
    table, vector_metadata = self.get_vector_table(vector_name, resampling_frequency, realizations)
  File "/home/appuser/backend/./src/services/sumo_access/summary_access.py", line 94, in get_vector_table
    raise ValueError("Table does not contain a DATE column")
ValueError: Table does not contain a DATE column
```

This would be valuable information to show to the user in the frontend, enabling them to fix the data in the database. We should however probably only send curated error message to the client (both for easier human consumption, but also in order to ensure not exposing secrets/variables).

**Comment by anders-kiaer** [comment]
The way to go within FastAPI is perhaps to use https://fastapi.tiangolo.com/tutorial/handling-errors/#use-httpexception in all exceptions raised in routes.

**Comment by anders-kiaer** [comment]
Done
